# Generated by Django 5.0.4 on 2024-06-26 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoCal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.alumno')),
                ('semestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.materia')),
            ],
        ),
    ]
