# Generated by Django 5.0.4 on 2024-06-26 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_tipocal'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificacion',
            name='parcial',
            field=models.IntegerField(choices=[(1, 'Parcial 1'), (2, 'Parcial 2'), (3, 'Parcial 3'), (4, 'Final')], default=4),
        ),
    ]
