# Generated by Django 5.0.4 on 2024-06-26 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_calificacion_parcial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelacionGrupoAlumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.alumno')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.grupos')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.materia')),
            ],
        ),
    ]
